# Valve game data analysis
### Dota 2

In [138]:
import dota2api
import numpy as np
import pandas as pd
from datetime import datetime as dt
from datetime import timedelta

In [139]:
api = dota2api.Initialise()

### This returns a dictionary of ticked games in progress

In [198]:
livegames = api.get_top_live_games()

In [170]:
livegames

{'game_list': [{'activate_time': 1531983488,
   'deactivate_time': 0,
   'server_steam_id': '90116251383297034',
   'lobby_id': '25700516562537501',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 602,
   'delay': 120,
   'spectators': 423,
   'game_mode': 22,
   'average_mmr': 6724,
   'sort_score': 7647,
   'last_update_time': 1531984256,
   'radiant_lead': 7281,
   'radiant_score': 15,
   'dire_score': 5,
   'players': [{'account_id': 130586940, 'hero_id': 37},
    {'account_id': 97590558, 'hero_id': 67},
    {'account_id': 40805086, 'hero_id': 34},
    {'account_id': 185718062, 'hero_id': 5},
    {'account_id': 346861819, 'hero_id': 58},
    {'account_id': 122041323, 'hero_id': 75},
    {'account_id': 169359249, 'hero_id': 1},
    {'account_id': 98018029, 'hero_id': 21},
    {'account_id': 91610743, 'hero_id': 47},
    {'account_id': 259975304, 'hero_id': 2}],
   'building_state': 4849737},
  {'activate_time': 1531982080,
   'deactivate_time': 0,
   'server_steam_id': '90116256718404616',
   'lobby_id': '25700516554658992',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 1820,
   'delay': 120,
   'spectators': 147,
   'game_mode': 22,
   'average_mmr': 6790,
   'sort_score': 7437,
   'last_update_time': 1531984256,
   'radiant_lead': 2268,
   'radiant_score': 37,
   'dire_score': 37,
   'players': [{'account_id': 196931374, 'hero_id': 8},
    {'account_id': 335490459, 'hero_id': 82},
    {'account_id': 206144913, 'hero_id': 70},
    {'account_id': 385295772, 'hero_id': 5},
    {'account_id': 106186122, 'hero_id': 31},
    {'account_id': 100895600, 'hero_id': 10},
    {'account_id': 121404228, 'hero_id': 83},
    {'account_id': 214335326, 'hero_id': 78},
    {'account_id': 117558174, 'hero_id': 119},
    {'account_id': 223867043, 'hero_id': 74}],
   'building_state': 20578450},
  {'activate_time': 1531982720,
   'deactivate_time': 0,
   'server_steam_id': '90116258614016010',
   'lobby_id': '25700516558024793',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 1393,
   'delay': 120,
   'spectators': 93,
   'game_mode': 22,
   'average_mmr': 6770,
   'sort_score': 7363,
   'last_update_time': 1531984256,
   'radiant_lead': -20254,
   'radiant_score': 13,
   'dire_score': 22,
   'players': [{'account_id': 112377459, 'hero_id': 100},
    {'account_id': 345525199, 'hero_id': 21},
    {'account_id': 157007358, 'hero_id': 22},
    {'account_id': 93616251, 'hero_id': 2},
    {'account_id': 111637216, 'hero_id': 67},
    {'account_id': 101897410, 'hero_id': 46},
    {'account_id': 109490722, 'hero_id': 101},
    {'account_id': 102500941, 'hero_id': 93},
    {'account_id': 209550959, 'hero_id': 5},
    {'account_id': 837609249, 'hero_id': 97}],
   'building_state': 4784346},
  {'activate_time': 1531981824,
   'deactivate_time': 0,
   'server_steam_id': '90116253614009344',
   'lobby_id': '25700516552533017',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 2214,
   'delay': 120,
   'spectators': 83,
   'game_mode': 22,
   'average_mmr': 6773,
   'sort_score': 7356,
   'last_update_time': 1531984256,
   'radiant_lead': -893,
   'radiant_score': 24,
   'dire_score': 35,
   'players': [{'account_id': 19195168, 'hero_id': 14},
    {'account_id': 329349567, 'hero_id': 111},
    {'account_id': 169817688, 'hero_id': 41},
    {'account_id': 86723143, 'hero_id': 27},
    {'account_id': 34322358, 'hero_id': 22},
    {'account_id': 106615943, 'hero_id': 119},
    {'account_id': 81640511, 'hero_id': 4},
    {'account_id': 302107336, 'hero_id': 39},
    {'account_id': 106028932, 'hero_id': 7},
    {'account_id': 56351509, 'hero_id': 99}],
   'building_state': 14614747},
  {'activate_time': 1531983616,
   'deactivate_time': 0,
   'server_steam_id': '90116258722187266',
   'lobby_id': '25700516563357878',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 374,
   'delay': 120,
   'spectators': 50,
   'game_mode': 22,
   'average_mmr': 6685,
   'sort_score': 7235,
   'last_update_time': 1531984256,
   'radiant_lead': 795,
   'radiant_score': 6,
   'dire_score': 3,
   'players': [{'account_id': 152896840, 'hero_id': 86},
    {'account_id': 153749549, 'hero_id': 9},
    {'account_id': 187478054, 'hero_id': 93},
    {'account_id': 151352096, 'hero_id': 120},
    {'account_id': 254013249, 'hero_id': 14},
    {'account_id': 240725371, 'hero_id': 16},
    {'account_id': 207983361, 'hero_id': 7},
    {'account_id': 115554677, 'hero_id': 76},
    {'account_id': 107227595, 'hero_id': 5},
    {'account_id': 316442339, 'hero_id': 95}],
   'building_state': 4784201},
  {'activate_time': 1531982848,
   'deactivate_time': 0,
   'server_steam_id': '90116256290254849',
   'lobby_id': '25700516558858495',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 1215,
   'delay': 120,
   'spectators': 79,
   'game_mode': 22,
   'average_mmr': 6643,
   'sort_score': 7222,
   'last_update_time': 1531984256,
   'radiant_lead': 13000,
   'radiant_score': 27,
   'dire_score': 11,
   'players': [{'account_id': 123931026, 'hero_id': 36},
    {'account_id': 141162261, 'hero_id': 5},
    {'account_id': 3940262, 'hero_id': 22},
    {'account_id': 102182118, 'hero_id': 41},
    {'account_id': 62552950, 'hero_id': 71},
    {'account_id': 184950344, 'hero_id': 9},
    {'account_id': 174702094, 'hero_id': 93},
    {'account_id': 135607261, 'hero_id': 83},
    {'account_id': 186347237, 'hero_id': 86},
    {'account_id': 95866780, 'hero_id': 106}],
   'building_state': 9633865},
  {'activate_time': 1531984128,
   'deactivate_time': 0,
   'server_steam_id': '90116257375825927',
   'lobby_id': '25700516566504626',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': -57,
   'delay': 120,
   'spectators': 9,
   'game_mode': 22,
   'average_mmr': 6705,
   'sort_score': 7214,
   'last_update_time': 1531984256,
   'radiant_lead': 68,
   'radiant_score': 0,
   'dire_score': 0,
   'players': [{'account_id': 86759987, 'hero_id': 58},
    {'account_id': 308423510, 'hero_id': 83},
    {'account_id': 155494381, 'hero_id': 79},
    {'account_id': 318067702, 'hero_id': 104},
    {'account_id': 102166192, 'hero_id': 109},
    {'account_id': 86874930, 'hero_id': 61},
    {'account_id': 110412761, 'hero_id': 21},
    {'account_id': 91516500, 'hero_id': 14},
    {'account_id': 124553723, 'hero_id': 72},
    {'account_id': 33256138, 'hero_id': 97}],
   'building_state': 4784201},
  {'activate_time': 1531984000,
   'deactivate_time': 0,
   'server_steam_id': '90116256316624896',
   'lobby_id': '25700516565767758',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 78,
   'delay': 120,
   'spectators': 6,
   'game_mode': 22,
   'average_mmr': 6639,
   'sort_score': 7145,
   'last_update_time': 1531984256,
   'radiant_lead': -251,
   'radiant_score': 0,
   'dire_score': 2,
   'players': [{'account_id': 80302009, 'hero_id': 119},
    {'account_id': 8157114, 'hero_id': 43},
    {'account_id': 112710750, 'hero_id': 5},
    {'account_id': 87084462, 'hero_id': 46},
    {'account_id': 872532737, 'hero_id': 33},
    {'account_id': 170638230, 'hero_id': 104},
    {'account_id': 102602749, 'hero_id': 100},
    {'account_id': 86747351, 'hero_id': 67},
    {'account_id': 139501180, 'hero_id': 84},
    {'account_id': 156745021, 'hero_id': 11}],
   'building_state': 4784201},
  {'activate_time': 1531982720,
   'deactivate_time': 0,
   'server_steam_id': '90116256137106434',
   'lobby_id': '25700516558006020',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 1187,
   'delay': 120,
   'spectators': 21,
   'game_mode': 22,
   'average_mmr': 6578,
   'sort_score': 7099,
   'last_update_time': 1531984256,
   'radiant_lead': 32,
   'radiant_score': 17,
   'dire_score': 16,
   'players': [{'account_id': 134566957, 'hero_id': 75},
    {'account_id': 408729743, 'hero_id': 88},
    {'account_id': 168059543, 'hero_id': 63},
    {'account_id': 59463394, 'hero_id': 49},
    {'account_id': 197574429, 'hero_id': 36},
    {'account_id': 212250618, 'hero_id': 45},
    {'account_id': 115141430, 'hero_id': 9},
    {'account_id': 110583422, 'hero_id': 114},
    {'account_id': 306654490, 'hero_id': 44},
    {'account_id': 107579110, 'hero_id': 103}],
   'building_state': 5374097},
  {'activate_time': 1531982208,
   'deactivate_time': 0,
   'server_steam_id': '90116254924407812',
   'lobby_id': '25700516555237265',
   'league_id': 0,
   'lobby_type': 7,
   'game_time': 1750,
   'delay': 120,
   'spectators': 16,
   'game_mode': 22,
   'average_mmr': 6577,
   'sort_score': 7093,
   'last_update_time': 1531984256,
   'radiant_lead': 6043,
   'radiant_score': 27,
   'dire_score': 29,
   'players': [{'account_id': 158074556, 'hero_id': 14},
    {'account_id': 202520908, 'hero_id': 104},
    {'account_id': 224623791, 'hero_id': 80},
    {'account_id': 30237211, 'hero_id': 45},
    {'account_id': 186837494, 'hero_id': 3},
    {'account_id': 28936989, 'hero_id': 70},
    {'account_id': 256964091, 'hero_id': 64},
    {'account_id': 209974969, 'hero_id': 9},
    {'account_id': 352062112, 'hero_id': 21},
    {'account_id': 77518613, 'hero_id': 36}],
   'building_state': 10223826}]}

In [171]:
livegames.keys()

dict_keys(['game_list'])

So, details of games can be extracted as:

In [199]:
df = pd.DataFrame(livegames["game_list"])
df.head()

,activate_time,average_mmr,building_state,deactivate_time,delay,dire_score,game_mode,game_time,last_update_time,league_id,lobby_id,lobby_type,players,radiant_lead,radiant_score,server_steam_id,sort_score,spectators
0,1531984384,6732,9633873,0,120,32,22,1534,1531986176,0,25700516568015427,7,"[{'account_id': 224568561, 'hero_id': 36}, {'a...",167,14,90116259808198663,7543,311
1,1531984896,6890,4784266,0,120,6,22,690,1531986176,0,25700516571805661,7,"[{'account_id': 104963314, 'hero_id': 22}, {'a...",-2500,10,90116259148816386,7505,115
2,1531985408,6792,4784201,0,120,7,22,447,1531986176,0,25700516574495404,7,"[{'account_id': 61215721, 'hero_id': 5}, {'acc...",1457,8,90116252214251526,7366,74
3,1531985664,6805,4784201,0,120,2,22,351,1531986176,0,25700516576194887,7,"[{'account_id': 109490722, 'hero_id': 119}, {'...",3176,4,90116259322473472,7342,37
4,1531985280,6791,12191305,0,120,1,22,534,1531986176,0,25700516574180903,7,"[{'account_id': 120901780, 'hero_id': 5}, {'ac...",18083,22,90116260272269313,7320,29

In [173]:
# last_updated = df["last_update_time"][0].astype("datetime64[s]")
# last_updated.astype(str), pd.DatetimeIndex([last_updated]).year.astype(str)
df["last_update_time"][0].astype("datetime64[s]").astype(str).replace("T"," ")

'2018-07-19 07:10:56'

In [174]:
df["players"][0]

[{'account_id': 130586940, 'hero_id': 37},
 {'account_id': 97590558, 'hero_id': 67},
 {'account_id': 40805086, 'hero_id': 34},
 {'account_id': 185718062, 'hero_id': 5},
 {'account_id': 346861819, 'hero_id': 58},
 {'account_id': 122041323, 'hero_id': 75},
 {'account_id': 169359249, 'hero_id': 1},
 {'account_id': 98018029, 'hero_id': 21},
 {'account_id': 91610743, 'hero_id': 47},
 {'account_id': 259975304, 'hero_id': 2}]

In [175]:
heroes = pd.DataFrame(api.get_heroes()["heroes"])
heroes.head()

,id,localized_name,name,url_full_portrait,url_large_portrait,url_small_portrait,url_vertical_portrait
0,1,Anti-Mage,npc_dota_hero_antimage,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...
1,2,Axe,npc_dota_hero_axe,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...
2,3,Bane,npc_dota_hero_bane,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...
3,4,Bloodseeker,npc_dota_hero_bloodseeker,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...
4,5,Crystal Maiden,npc_dota_hero_crystal_maiden,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...,http://cdn.dota2.com/apps/dota2/images/heroes/...

In [176]:
heroes[heroes["id"]==5].localized_name.values[0]

'Crystal Maiden'

In [177]:
df.dtypes

activate_time        int64
average_mmr          int64
building_state       int64
deactivate_time      int64
delay                int64
dire_score           int64
game_mode            int64
game_time            int64
last_update_time     int64
league_id            int64
lobby_id            object
lobby_type           int64
players             object
radiant_lead         int64
radiant_score        int64
server_steam_id     object
sort_score           int64
spectators           int64
dtype: object

In [178]:
for i in range(10):
    df["player{}".format(i+1)] = df["players"].apply(lambda x: x[i]["account_id"])
    df["hero{}".format(i+1)] = df["players"].apply(lambda x: x[i]["hero_id"])
#     .apply(lambda x: heroes[heroes["id"]==x].localized_name.values[0])
df.head()

,activate_time,average_mmr,building_state,deactivate_time,delay,dire_score,game_mode,game_time,last_update_time,league_id,...,player6,hero6,player7,hero7,player8,hero8,player9,hero9,player10,hero10
0,1531983488,6724,4849737,0,120,5,22,602,1531984256,0,...,122041323,75,169359249,1,98018029,21,91610743,47,259975304,2
1,1531982080,6790,20578450,0,120,37,22,1820,1531984256,0,...,100895600,10,121404228,83,214335326,78,117558174,119,223867043,74
2,1531982720,6770,4784346,0,120,22,22,1393,1531984256,0,...,101897410,46,109490722,101,102500941,93,209550959,5,837609249,97
3,1531981824,6773,14614747,0,120,35,22,2214,1531984256,0,...,106615943,119,81640511,4,302107336,39,106028932,7,56351509,99
4,1531983616,6685,4784201,0,120,3,22,374,1531984256,0,...,240725371,16,207983361,7,115554677,76,107227595,5,316442339,95

In [179]:
df.dtypes

activate_time        int64
average_mmr          int64
building_state       int64
deactivate_time      int64
delay                int64
dire_score           int64
game_mode            int64
game_time            int64
last_update_time     int64
league_id            int64
lobby_id            object
lobby_type           int64
players             object
radiant_lead         int64
radiant_score        int64
server_steam_id     object
sort_score           int64
spectators           int64
player1              int64
hero1                int64
player2              int64
hero2                int64
player3              int64
hero3                int64
player4              int64
hero4                int64
player5              int64
hero5                int64
player6              int64
hero6                int64
player7              int64
hero7                int64
player8              int64
hero8                int64
player9              int64
hero9                int64
player10             int64
hero10               int64
dtype: object

In [180]:
try:
    for i in range(10):
        df["hero{}".format(i+1)] = df["hero{}".format(i+1)].apply(lambda x: heroes[heroes["id"]==x].localized_name.values[0])
except Exception as e:
    print("Data Acquiring, picking stage for a top spectating game! Please check back in a minute.")
    print(str(e))
df

,activate_time,average_mmr,building_state,deactivate_time,delay,dire_score,game_mode,game_time,last_update_time,league_id,...,player6,hero6,player7,hero7,player8,hero8,player9,hero9,player10,hero10
0,1531983488,6724,4849737,0,120,5,22,602,1531984256,0,...,122041323,Silencer,169359249,Anti-Mage,98018029,Windranger,91610743,Viper,259975304,Axe
1,1531982080,6790,20578450,0,120,37,22,1820,1531984256,0,...,100895600,Morphling,121404228,Treant Protector,214335326,Brewmaster,117558174,Dark Willow,223867043,Invoker
2,1531982720,6770,4784346,0,120,22,22,1393,1531984256,0,...,101897410,Templar Assassin,109490722,Skywrath Mage,102500941,Slark,209550959,Crystal Maiden,837609249,Magnus
3,1531981824,6773,14614747,0,120,35,22,2214,1531984256,0,...,106615943,Dark Willow,81640511,Bloodseeker,302107336,Queen of Pain,106028932,Earthshaker,56351509,Bristleback
4,1531983616,6685,4784201,0,120,3,22,374,1531984256,0,...,240725371,Sand King,207983361,Earthshaker,115554677,Outworld Devourer,107227595,Crystal Maiden,316442339,Troll Warlord
5,1531982848,6643,9633865,0,120,11,22,1215,1531984256,0,...,184950344,Mirana,174702094,Slark,135607261,Treant Protector,186347237,Rubick,95866780,Ember Spirit
6,1531984128,6705,4784201,0,120,0,22,-57,1531984256,0,...,86874930,Broodmother,110412761,Windranger,91516500,Pudge,124553723,Gyrocopter,33256138,Magnus
7,1531984000,6639,4784201,0,120,2,22,78,1531984256,0,...,170638230,Legion Commander,102602749,Tusk,86747351,Spectre,139501180,Ogre Magi,156745021,Shadow Fiend
8,1531982720,6578,5374097,0,120,16,22,1187,1531984256,0,...,212250618,Pugna,115141430,Mirana,110583422,Monkey King,306654490,Phantom Assassin,107579110,Elder Titan
9,1531982208,6577,10223826,0,120,29,22,1750,1531984256,0,...,28936989,Ursa,256964091,Jakiro,209974969,Mirana,352062112,Windranger,77518613,Necrophos

In [181]:
def GetTime(seconds):
    d = dt(1,1,1) + timedelta(seconds=int(seconds))
    return {"hour":d.hour, "min":d.minute, "sec":d.second}

In [182]:
insecs = df["game_time"][0]
insecs

602

In [183]:
GetTime(insecs)

{'hour': 0, 'min': 10, 'sec': 2}

In [184]:
df["game_time_min"] = df["game_time"].apply(lambda x: int((dt(1,1,1) + timedelta(seconds=x)).minute) if x > 0 else 0)
df["game_time_sec"] = df["game_time"].apply(lambda x: int((dt(1,1,1) + timedelta(seconds=x)).second) if x > 0 else x)
df

,activate_time,average_mmr,building_state,deactivate_time,delay,dire_score,game_mode,game_time,last_update_time,league_id,...,player7,hero7,player8,hero8,player9,hero9,player10,hero10,game_time_min,game_time_sec
0,1531983488,6724,4849737,0,120,5,22,602,1531984256,0,...,169359249,Anti-Mage,98018029,Windranger,91610743,Viper,259975304,Axe,10,2
1,1531982080,6790,20578450,0,120,37,22,1820,1531984256,0,...,121404228,Treant Protector,214335326,Brewmaster,117558174,Dark Willow,223867043,Invoker,30,20
2,1531982720,6770,4784346,0,120,22,22,1393,1531984256,0,...,109490722,Skywrath Mage,102500941,Slark,209550959,Crystal Maiden,837609249,Magnus,23,13
3,1531981824,6773,14614747,0,120,35,22,2214,1531984256,0,...,81640511,Bloodseeker,302107336,Queen of Pain,106028932,Earthshaker,56351509,Bristleback,36,54
4,1531983616,6685,4784201,0,120,3,22,374,1531984256,0,...,207983361,Earthshaker,115554677,Outworld Devourer,107227595,Crystal Maiden,316442339,Troll Warlord,6,14
5,1531982848,6643,9633865,0,120,11,22,1215,1531984256,0,...,174702094,Slark,135607261,Treant Protector,186347237,Rubick,95866780,Ember Spirit,20,15
6,1531984128,6705,4784201,0,120,0,22,-57,1531984256,0,...,110412761,Windranger,91516500,Pudge,124553723,Gyrocopter,33256138,Magnus,0,-57
7,1531984000,6639,4784201,0,120,2,22,78,1531984256,0,...,102602749,Tusk,86747351,Spectre,139501180,Ogre Magi,156745021,Shadow Fiend,1,18
8,1531982720,6578,5374097,0,120,16,22,1187,1531984256,0,...,115141430,Mirana,110583422,Monkey King,306654490,Phantom Assassin,107579110,Elder Titan,19,47
9,1531982208,6577,10223826,0,120,29,22,1750,1531984256,0,...,256964091,Jakiro,209974969,Mirana,352062112,Windranger,77518613,Necrophos,29,10

In [185]:
df["game_time"] = df.apply(lambda x: str(x.game_time_min) + ":" + str(x.game_time_sec), axis=1)
df

,activate_time,average_mmr,building_state,deactivate_time,delay,dire_score,game_mode,game_time,last_update_time,league_id,...,player7,hero7,player8,hero8,player9,hero9,player10,hero10,game_time_min,game_time_sec
0,1531983488,6724,4849737,0,120,5,22,10:2,1531984256,0,...,169359249,Anti-Mage,98018029,Windranger,91610743,Viper,259975304,Axe,10,2
1,1531982080,6790,20578450,0,120,37,22,30:20,1531984256,0,...,121404228,Treant Protector,214335326,Brewmaster,117558174,Dark Willow,223867043,Invoker,30,20
2,1531982720,6770,4784346,0,120,22,22,23:13,1531984256,0,...,109490722,Skywrath Mage,102500941,Slark,209550959,Crystal Maiden,837609249,Magnus,23,13
3,1531981824,6773,14614747,0,120,35,22,36:54,1531984256,0,...,81640511,Bloodseeker,302107336,Queen of Pain,106028932,Earthshaker,56351509,Bristleback,36,54
4,1531983616,6685,4784201,0,120,3,22,6:14,1531984256,0,...,207983361,Earthshaker,115554677,Outworld Devourer,107227595,Crystal Maiden,316442339,Troll Warlord,6,14
5,1531982848,6643,9633865,0,120,11,22,20:15,1531984256,0,...,174702094,Slark,135607261,Treant Protector,186347237,Rubick,95866780,Ember Spirit,20,15
6,1531984128,6705,4784201,0,120,0,22,0:-57,1531984256,0,...,110412761,Windranger,91516500,Pudge,124553723,Gyrocopter,33256138,Magnus,0,-57
7,1531984000,6639,4784201,0,120,2,22,1:18,1531984256,0,...,102602749,Tusk,86747351,Spectre,139501180,Ogre Magi,156745021,Shadow Fiend,1,18
8,1531982720,6578,5374097,0,120,16,22,19:47,1531984256,0,...,115141430,Mirana,110583422,Monkey King,306654490,Phantom Assassin,107579110,Elder Titan,19,47
9,1531982208,6577,10223826,0,120,29,22,29:10,1531984256,0,...,256964091,Jakiro,209974969,Mirana,352062112,Windranger,77518613,Necrophos,29,10

In [186]:
dota2api.src.parse.game_mode(api.get_match_details(match_id=1000193456))["game_mode_name"]

'Captains Draft'

In [187]:
[(i,d) for i,d in enumerate(df.columns)]

[(0, 'activate_time'),
 (1, 'average_mmr'),
 (2, 'building_state'),
 (3, 'deactivate_time'),
 (4, 'delay'),
 (5, 'dire_score'),
 (6, 'game_mode'),
 (7, 'game_time'),
 (8, 'last_update_time'),
 (9, 'league_id'),
 (10, 'lobby_id'),
 (11, 'lobby_type'),
 (12, 'players'),
 (13, 'radiant_lead'),
 (14, 'radiant_score'),
 (15, 'server_steam_id'),
 (16, 'sort_score'),
 (17, 'spectators'),
 (18, 'player1'),
 (19, 'hero1'),
 (20, 'player2'),
 (21, 'hero2'),
 (22, 'player3'),
 (23, 'hero3'),
 (24, 'player4'),
 (25, 'hero4'),
 (26, 'player5'),
 (27, 'hero5'),
 (28, 'player6'),
 (29, 'hero6'),
 (30, 'player7'),
 (31, 'hero7'),
 (32, 'player8'),
 (33, 'hero8'),
 (34, 'player9'),
 (35, 'hero9'),
 (36, 'player10'),
 (37, 'hero10'),
 (38, 'game_time_min'),
 (39, 'game_time_sec')]

#### average_mmr, dire_score, radiant_score, game_time_min, game_time_sec, spectators, radiant_lead(-ve if dire_lead),

In [188]:
ga = df.iloc[:,[1,17,5,14,39,40]]
p = df.iloc[:,19:39]
ga

IndexError: positional indexers are out-of-bounds

In [51]:
p

,player1,hero1,player2,hero2,player3,hero3,player4,hero4,player5,hero5,player6,hero6,player7,hero7,player8,hero8,player9,hero9,player10,hero10
0,119631156,Dark Willow,358579220,Razor,107485519,Monkey King,84105632,Phoenix,86847476,Crystal Maiden,539524828,Winter Wyvern,30237211,Necrophos,221666230,Tiny,146485028,Weaver,212250618,Clockwerk
1,156745021,Shadow Fiend,82051518,Axe,8157114,Dark Willow,110448679,Crystal Maiden,28936989,Bloodseeker,25502245,Necrophos,88153289,Pudge,102304762,Treant Protector,168059543,Timbersaw,85937380,Invoker
2,122021562,Lich,100311765,Doom,363532909,Invoker,240725371,Lion,102473287,Faceless Void,94531730,Crystal Maiden,143278997,Zeus,253897281,Templar Assassin,207105991,Enigma,358367084,Bloodseeker
3,118306480,Wraith King,126702445,Necrophos,872952506,Witch Doctor,401792574,Pugna,37364878,Elder Titan,90365989,Pudge,185718062,Windranger,86897891,Nyx Assassin,176139572,Ursa,104635607,Faceless Void
4,82127698,Warlock,86793739,Windranger,367998802,Crystal Maiden,20321748,Tiny,151575011,Spectre,457747026,Jakiro,9403474,Pudge,89128606,Necrophos,166639117,Lycan,295547527,Lifestealer
5,87037608,Skywrath Mage,111620041,Shadow Fiend,123189159,Weaver,177953305,Tusk,135025253,Pangolier,106781506,Crystal Maiden,5448108,Elder Titan,126238768,Templar Assassin,44461910,Faceless Void,202520908,Mirana
6,102224057,Undying,38628747,Queen of Pain,173905063,Bloodseeker,170638230,Centaur Warrunner,48124103,Witch Doctor,83577790,Juggernaut,101779337,Windranger,160119017,Shadow Fiend,371759313,Crystal Maiden,100246000,Riki
7,874233645,Spectre,402485097,Storm Spirit,54075055,Crystal Maiden,69282131,Windranger,179865964,Sand King,97377892,Brewmaster,168785654,Chaos Knight,103848086,Leshrac,159020918,Ursa,26952,Shadow Demon
8,339653788,Warlock,237201026,Meepo,167433620,Pudge,89654154,Faceless Void,324272909,Magnus,257506379,Phantom Lancer,127657459,Necrophos,171646801,Bounty Hunter,172114806,Crystal Maiden,94374420,Nature's Prophet
9,91907884,Warlock,54151884,Templar Assassin,197952035,Nyx Assassin,868568216,Juggernaut,860864977,Ursa,112594983,Jakiro,91610743,Broodmother,170693921,Invoker,69312046,Centaur Warrunner,104206045,Zeus

In [58]:
[col for col in ga.columns.values]

['average_mmr',
 'spectators',
 'dire_score',
 'radiant_score',
 'game_time_min',
 'game_time_sec']

In [106]:
[i for i in pd.DataFrame(api.get_top_live_games()["game_list"])["players"]]

[[{'account_id': 432516198, 'hero_id': 9},
  {'account_id': 168089239, 'hero_id': 120},
  {'account_id': 169756712, 'hero_id': 14},
  {'account_id': 281790498, 'hero_id': 41},
  {'account_id': 372022646, 'hero_id': 5},
  {'account_id': 405535223, 'hero_id': 100},
  {'account_id': 292829433, 'hero_id': 119},
  {'account_id': 205128419, 'hero_id': 114},
  {'account_id': 116585378, 'hero_id': 74},
  {'account_id': 115438858, 'hero_id': 89}],
 [{'account_id': 166868559, 'hero_id': 21},
  {'account_id': 335490459, 'hero_id': 59},
  {'account_id': 389033587, 'hero_id': 113},
  {'account_id': 103208524, 'hero_id': 7},
  {'account_id': 297312417, 'hero_id': 19},
  {'account_id': 191607069, 'hero_id': 51},
  {'account_id': 181716137, 'hero_id': 49},
  {'account_id': 153749549, 'hero_id': 9},
  {'account_id': 316442339, 'hero_id': 95},
  {'account_id': 187478054, 'hero_id': 5}],
 [{'account_id': 86726887, 'hero_id': 75},
  {'account_id': 84105632, 'hero_id': 4},
  {'account_id': 86811043, 'hero_id': 119},
  {'account_id': 141146712, 'hero_id': 112},
  {'account_id': 146485028, 'hero_id': 10},
  {'account_id': 197574429, 'hero_id': 25},
  {'account_id': 315657960, 'hero_id': 42},
  {'account_id': 370966003, 'hero_id': 53},
  {'account_id': 149921463, 'hero_id': 64},
  {'account_id': 59752811, 'hero_id': 71}],
 [{'account_id': 169817688, 'hero_id': 9},
  {'account_id': 360433808, 'hero_id': 37},
  {'account_id': 9403474, 'hero_id': 119},
  {'account_id': 202508980, 'hero_id': 2},
  {'account_id': 55649904, 'hero_id': 70},
  {'account_id': 398585034, 'hero_id': 3},
  {'account_id': 91735466, 'hero_id': 102},
  {'account_id': 124066939, 'hero_id': 14},
  {'account_id': 54151884, 'hero_id': 25},
  {'account_id': 176139572, 'hero_id': 41}],
 [{'account_id': 124168390, 'hero_id': 8},
  {'account_id': 170638230, 'hero_id': 2},
  {'account_id': 150296940, 'hero_id': 75},
  {'account_id': 8157114, 'hero_id': 86},
  {'account_id': 119743955, 'hero_id': 11},
  {'account_id': 123953528, 'hero_id': 17},
  {'account_id': 76173488, 'hero_id': 5},
  {'account_id': 105178768, 'hero_id': 21},
  {'account_id': 170041034, 'hero_id': 36},
  {'account_id': 87177591, 'hero_id': 6}],
 [{'account_id': 872532737, 'hero_id': 6},
  {'account_id': 128660724, 'hero_id': 21},
  {'account_id': 539524828, 'hero_id': 46},
  {'account_id': 134566957, 'hero_id': 119},
  {'account_id': 100758751, 'hero_id': 104},
  {'account_id': 209974969, 'hero_id': 41},
  {'account_id': 242697694, 'hero_id': 97},
  {'account_id': 115141430, 'hero_id': 64},
  {'account_id': 109859658, 'hero_id': 101},
  {'account_id': 101779337, 'hero_id': 7}],
 [{'account_id': 132538905, 'hero_id': 119},
  {'account_id': 35334936, 'hero_id': 5},
  {'account_id': 484158991, 'hero_id': 67},
  {'account_id': 202520908, 'hero_id': 9},
  {'account_id': 133976297, 'hero_id': 83},
  {'account_id': 187191278, 'hero_id': 46},
  {'account_id': 368273843, 'hero_id': 49},
  {'account_id': 100246000, 'hero_id': 114},
  {'account_id': 67428263, 'hero_id': 21},
  {'account_id': 100488804, 'hero_id': 36}],
 [{'account_id': 100311765, 'hero_id': 4},
  {'account_id': 195804179, 'hero_id': 5},
  {'account_id': 104747843, 'hero_id': 88},
  {'account_id': 154809742, 'hero_id': 56},
  {'account_id': 431497040, 'hero_id': 14},
  {'account_id': 122704314, 'hero_id': 120},
  {'account_id': 94531730, 'hero_id': 26},
  {'account_id': 157007358, 'hero_id': 74},
  {'account_id': 33256138, 'hero_id': 103},
  {'account_id': 107897138, 'hero_id': 54}],
 [{'account_id': 86747351, 'hero_id': 44},
  {'account_id': 366166639, 'hero_id': 21},
  {'account_id': 300222966, 'hero_id': 87},
  {'account_id': 104275965, 'hero_id': 104},
  {'account_id': 287481472, 'hero_id': 45},
  {'account_id': 102588710, 'hero_id': 5},
  {'account_id': 352623024, 'hero_id': 2},
  {'account_id': 119631156, 'hero_id': 119},
  {'account_id': 118207269, 'hero_id': 36},
  {'account_id': 110448679, 'hero_id': 11}],
 [{'account_id': 224568561, 'hero_id': 9},
  {'account_id': 345756701, 'hero_id': 114},
  {'account_id': 237325411, 'hero_id': 27},
  {'account_id': 101897410, 'hero_id': 36},
  {'account_id': 105610776, 'hero_id': 14},
  {'account_id': 140666974, 'hero_id': 5},
  {'account_id': 171455162, 'hero_id': 71},
  {'account_id': 104124811, 'hero_id': 82},
  {'account_id': 257506379, 'hero_id': 120},
  {'account_id': 134741940, 'hero_id': 12}]]

In [166]:
minute = 2
second = 30
"{:02}:{:02}".format(minute,second)

'02:30'

In [189]:
d = pd.DataFrame({"a":[1,2,3],"b":[3,4,5]})
d

   a  b
0  1  3
1  2  4
2  3  5

In [191]:
type(d.iloc[:,0])

pandas.core.series.Series

In [197]:
xxxx=1
a = [1]
while(True):
    try:
        print(a[20])
        xxxx=2
        break
    except Exception as e:
        print(str(e))
        a.append(1)
print(xxxx)

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
1
2

In [204]:
pd.DataFrame(api.get_top_live_games()["game_list"])

,activate_time,average_mmr,building_state,deactivate_time,delay,dire_score,game_mode,game_time,last_update_time,league_id,lobby_id,lobby_type,players,radiant_lead,radiant_score,server_steam_id,sort_score,spectators
0,1531984384,6732,14352611,0,120,48,22,2075,1531986688,0,25700516568015427,7,"[{'account_id': 224568561, 'hero_id': 36}, {'a...",-14908,19,90116259808198663,7985,753
1,1531986432,7126,4784201,0,120,0,22,30,1531986688,0,25700516581488257,7,"[{'account_id': 100246000, 'hero_id': 114}, {'...",94,0,90116258992247817,7817,191
2,1531986432,7062,4784201,0,120,1,22,139,1531986688,0,25700516580848362,7,"[{'account_id': 116585378, 'hero_id': 25}, {'a...",-1175,0,90116260622887947,7707,145
3,1531984896,6890,5308563,0,120,18,22,1237,1531986688,0,25700516571805661,7,"[{'account_id': 104963314, 'hero_id': 22}, {'a...",-531,21,90116259148816386,7538,148
4,1531985408,6792,10092681,0,120,13,22,1001,1531986688,0,25700516574495404,7,"[{'account_id': 61215721, 'hero_id': 5}, {'acc...",3298,18,90116252214251526,7462,170
5,1531985664,6805,9568329,0,120,10,22,881,1531986688,0,25700516576194887,7,"[{'account_id': 109490722, 'hero_id': 119}, {'...",3192,15,90116259322473472,7394,89
6,1531985792,6722,5374025,0,120,10,22,747,1531986688,0,25700516577106335,7,"[{'account_id': 94554991, 'hero_id': 85}, {'ac...",2841,11,90116253262950403,7250,28
7,1531986304,6714,4784201,0,120,3,22,160,1531986688,0,25700516580848340,7,"[{'account_id': 254013249, 'hero_id': 25}, {'a...",-856,0,90116260415448067,7226,12
8,1531986048,6664,4784201,0,120,2,22,476,1531986688,0,25700516578540421,7,"[{'account_id': 110583422, 'hero_id': 92}, {'a...",37,4,90116253490836482,7198,34
9,1531985024,6681,5308626,0,120,27,22,1482,1531986688,0,25700516572585094,7,"[{'account_id': 120090915, 'hero_id': 2}, {'ac...",-11451,17,90116259882676231,7195,14